version: '3.8'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: nodejs-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
    depends_on:
      - mariadb

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: mariadb-container
    ports:
      - '3306:3306'
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
