FROM mariadb:latest

# Install MariaDB client
RUN apt-get update && apt-get install -y mariadb-client

# Copy initialization scripts
COPY ./dbinit/init.sql /docker-entrypoint-initdb/0_init.sql

# Expose the default port for MariaDB
EXPOSE 3306